### ISSUE TITLE
Missing library libRlapack.dylib

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#88]
With RRO-8.0.1-beta2
Some packages, including igraph, fail to load due to missing library 

```
> install.packages("igraph")
trying URL 'http://mran.revolutionanalytics.com/snapshot/2014-12-01/bin/macosx/mavericks/contrib/3.1/igraph_0.7.1.tgz'
Content type 'application/octet-stream' length 5677163 bytes (5.4 Mb)
opened URL
==================================================
downloaded 5.4 Mb


The downloaded binary packages are in
	/var/folders/hy/wcdcll0j0m3bf0_c14dgm3zh0000gn/T//RtmpN8CBPl/downloaded_packages
> library(igraph)
Error : .onLoad failed in loadNamespace() for 'igraph', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/igraph/libs/igraph.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.1/Resources/library/igraph/libs/igraph.so, 10): Library not loaded: /Library/Frameworks/R.framework/Versions/3.1/Resources/lib/libRlapack.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.1/Resources/library/igraph/libs/igraph.so
  Reason: image not found
Error: package or namespace load failed for ‘igraph’
> 
```

As a workaround, you can install R, then install RRO. There seem to be a number of libraries missing, that are replaced by installing R first. This is with RRO installed:

```
Davids-Air-2:R david$ cd /Library/Frameworks/R.framework/Versions/3.1/Resources/lib
Davids-Air-2:lib david$ ls
libR.dylib		libgfortran.3.dylib	libreadline.dylib
libgcc_s.1.dylib	libquadmath.0.dylib
libgcc_s_x86_64.1.dylib	libreadline.6.3.dylib
```
And this is after installing R on top of RRO:
```
Davids-Air-2:lib david$ ls
libR.dylib		libRlapack.dylib	libquadmath.0.dylib
libR.dylib.dSYM		libRlapack.dylib.dSYM	libreadline.5.2.dylib
libRblas.0.dylib	libgcc_s.1.dylib	libreadline.6.3.dylib
libRblas.dylib		libgcc_s_x86_64.1.dylib	libreadline.dylib
libRblas.dylib.dSYM	libgfortran.3.dylib
```

**Comment by revodavid** [comment]
Workaround on release notes: https://github.com/RevolutionAnalytics/RRO/releases/tag/v8.0.1-beta2

**Comment by revodavid** [comment]
Verified fixed in 8.0.2 Beta 1.

**Comment by lfdmotta** [comment]
This issue is still present in Microsoft R Open 3.3.2 released on Nov 2016.

As a workaround, I downloaded the CRAN R installation package for macOS and copied the missing dylib files to /Library/Frameworks/R.framework/ ...

**Comment by bchen102** [comment]
The issue is still present in Microsoft R Open 3.3.4.

**Comment by RafalLukawiecki** [comment]
This issue is still present in Microsoft R Open 3.4.1, just tested. Trying to install package nleqslv:

```
> install.packages("nleqslv")
trying URL 'https://mran.microsoft.com/snapshot/2017-09-01/bin/macosx/el-capitan/contrib/3.4/nleqslv_3.3.1.tgz'
Content type 'application/octet-stream' length 144154 bytes (140 KB)
==================================================
downloaded 140 KB


The downloaded binary packages are in
	/var/folders/36/wj721rh15jgggpylc0gh2tf40000gn/T//RtmpiqVsrv/downloaded_packages
> library("nleqslv")
Error: package or namespace load failed for ‘nleqslv’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4.1-MRO/Resources/library/nleqslv/libs/nleqslv.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4.1-MRO/Resources/library/nleqslv/libs/nleqslv.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4.1-MRO/Resources/library/nleqslv/libs/nleqslv.so
  Reason: image not found
```

**Comment by amandeepjutla** [comment]
Ran into this issue trying to load the imputeTS package with MRO 3.5.1:

```
Error: package or namespace load failed for ‘imputeTS’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5.1-MRO/Resources/library/fracdiff/libs/fracdiff.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5.1-MRO/Resources/library/fracdiff/libs/fracdiff.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5.1-MRO/Resources/library/fracdiff/libs/fracdiff.so
  Reason: image not found
```

Had to manually extract `libRblas.dylib` from a vanilla R package and place it into /Library/Frameworks/R.framework/Versions/3.5/Resources/lib.
